// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PO_StandardFont","status":true,"description":"Always Use GameFont for StandardFont v0.0.1","parameters":{}},
{"name":"ChangeResolution","status":true,"description":"解像度を変更します。","parameters":{"width":"1104","height":"624"}},
{"name":"PO_MessageForResolution","status":true,"description":"Center the Message v0.0.1","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"VE_BasicModule","status":true,"description":"v1.23 - Plugin with base code required for all Victor Engine plugins.","parameters":{"== Trait Names ==":"","Hit Rate Name":"Hit","Evasion Rate Name":"Evasion","Critical Rate Name":"Critical","Critical Evasion Name":"C. Evasion","Magic Evasion Name":"M. Evasion","Magic Reflection Name":"M. Reflection","Counter Attack Name":"Counter","HP Regeneration Name":"HP Regen","MP Regeneration Name":"MP Regen","TP Regeneration Name":"TP Regen","Target Rate Name":"Target Rate","Guard Rate Name":"Guard Rate","Recovery Effect Name":"Recovery","Pharmacology Name":"Pharmacology","MP Cost Rate Name":"MP Cost","TP Charge Rate Name":"TP Charge","Physical Damage Name":"Physical Damage","Magical Damage Name":"Magical Damage","Floor Damage Name":"Floor Damage","Experience Rate Name":"Exp. Rate\r"}},
{"name":"VE_CooperationSkills","status":true,"description":"v1.00 - Battlers join to execute actions together.","parameters":{}},
{"name":"AltClassDisplay","status":true,"description":"Alternative Display of Class Name.","parameters":{}},
{"name":"IRPP_MV_MenuStatusRows","status":true,"description":"(※最上部)メニュー画面のアクターの表示人数を調整します。","parameters":{"MenuStatusRows":"6"}},
{"name":"IRPP_MV_ParamMaxEX","status":true,"description":"能力値の最大値を指定します。","parameters":{"Page1":"","Max MHP Actor":"99999","Max MMP Actor":"99999","Max ATK Actor":"9999","Max DEF Actor":"9999","Max MAT Actor":"9999","Max MDF Actor":"9999","Max AGI Actor":"9999","Max LUK Actor":"9999","Page2":"","Max MHP Enemy":"999999","Max MMP Enemy":"99999","Max ATK Enemy":"9999","Max DEF Enemy":"9999","Max MAT Enemy":"9999","Max MDF Enemy":"9999","Max AGI Enemy":"9999","Max LUK Enemy":"9999"}},
{"name":"PO_PartyMaxMembers","status":true,"description":"Party Max Members Size Changes v0.0.1","parameters":{"Max Battle Members Size":"6"}},
{"name":"ConditionallyCore","status":true,"description":"ver1.07/条件付き○○のプラグインを使用するのに、必要となる条件をまとめたベースプラグインです。","parameters":{}},
{"name":"PhaseSkillTrait","status":true,"description":"ver1.06/条件を満たすと戦闘開始時やターン開始時、ターン終了時等にスキルを発動する特徴を設定できるようになります。","parameters":{"Invoke Count":"1","Invoke Count Subject":"1","Sort Type":"2","Battle Start Skill Text":"\\C[10]_nameの先制スキルが発動した！","Turn Start Skill Text":"_nameのスタートフェイズスキルが発動した！","Turn End Skill Text":"_nameのエンドフェイズスキルが発動した！","Is Display Use Log":"false"}},
{"name":"PassiveSkill","status":true,"description":"ver1.061/スキルに特徴を設定できるようにします。","parameters":{"Passive Skill Type ID":"3","Add Multi Order":"true"}},
{"name":"Torigoya_SameEquipType","status":true,"description":"If equip slot name is the same, it can have an item of the same type","parameters":{}},
{"name":"111_InputForm","status":true,"description":"フォーム作って文字入力（修正版）","parameters":{}},
{"name":"Autolife","status":true,"description":"Special State: Autolife v1.1.0","parameters":{"Autolife Animation ID":"49"}},
{"name":"NoWeaponDisabled","status":true,"description":"Disable no weapon in equip screen.","parameters":{}},
{"name":"TYA_EnemyHPGauge","status":true,"description":"敵ターゲットウィンドウにＨＰゲージを表示させます。\r\n特定の敵のゲージを非表示にすることもできます。","parameters":{}},
{"name":"TMTpReset","status":true,"description":"戦闘開始時の初期ＴＰを調整します。","parameters":{"startTp":"0","startVariableTp":"0","startTpVariance":"0"}},
{"name":"TMMaxItems","status":true,"description":"アイテムの所持上限数を個別に設定します。","parameters":{"numberMaxDigits":"4","numberFontSize":"24","numberSeparator":"×"}},
{"name":"TMGreedShop","status":true,"description":"お金以外にアイテムも要求されるショップ機能を追加します。","parameters":{"materialWindowPosition":"0","materialWindowWidth":"408","buyWindowWidth":"456","buyWindowHeight":"0","materialMax":"5","fontRate":"0.8","greedCommand":"合成する","needText":"必要なもの","showSellCommand":"true","showMaterialWindow":"true","overlaid":"true","backOpacity":"192","showMaterialFromNumberWindow":"true","showPrice":"true","seGreedBuy":"{\"name\":\"Shop1\",\"volume\":\"90\",\"pitch\":\"100\",\"pan\":\"0\"}"}},
{"name":"Rubi_riru","status":true,"description":"ルビ振りを行います。用語登録によるオートルビ振り機能つき。","parameters":{"Auto Ruby":"false","Help Auto Ruby":"false","Database Auto Ruby":"false","Jisage":"2","Ruby Size":"-2"}},
{"name":"TKM_ChoiceList","status":true,"description":"TKM_ChoiceList","parameters":{"use":"false","-- Choice settings --":"","image":"","tone":"100, -40, 40","fontSize":"28","okFlashDuration":"30","okFlashFrequency":"4","textAlign":"0","-- Advanced settings --":"","backOpacity":"255","fontOLWidth":"3","fontOLColor":"rgba(0, 0, 0, 0.5)","vertiPadding":"8","choiceHoriPadding":"32","choiceVertiPadding":"5","maxRows":"4","maxRowsC":"3","mineLineWidth":"96"}}
];
